Repository CalmCrews/silver_frontend, pull requests merged in 2023-08, with the labels that each got.

#4 Style signup
  .env
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/ReviewInput.tsx
  src/components/SignInForm.tsx
  src/components/SignUpForm.tsx
  src/components/SimpleAppBar.tsx
  src/components/SpeechToText.tsx
  src/index.tsx
  src/pages/Home.tsx
  src/pages/testing/Review.tsx
  src/pages/users/SignIn.tsx
  src/pages/users/SignUp.tsx
  src/states/userInfo.ts
  src/theme/theme.ts
  tsconfig.json
Labels: ✨ Feature, 🎨 Html&css

#6 Feature split signup
  src/App.tsx
  src/assets/icons/CheckedIcon.png
  src/assets/icons/WarningIcon.png
  src/components/SignUpForm.tsx
  src/components/shared/DefaultIcon.tsx
  src/components/shared/FormButton.tsx
  src/components/user/SignupIdForm.tsx
  src/components/user/SignupPsForm.tsx
  src/fonts/pretendard.css
  src/fonts/woff/Pretendard-Black.woff
  src/fonts/woff/Pretendard-Bold.woff
  src/fonts/woff/Pretendard-ExtraBold.woff
  src/fonts/woff/Pretendard-ExtraLight.woff
  src/fonts/woff/Pretendard-Light.woff
  src/fonts/woff/Pretendard-Medium.woff
  src/fonts/woff/Pretendard-Regular.woff
  src/fonts/woff/Pretendard-SemiBold.woff
  src/fonts/woff/Pretendard-Thin.woff
  src/fonts/woff2/Pretendard-Black.woff2
  src/fonts/woff2/Pretendard-Bold.woff2
  src/fonts/woff2/Pretendard-ExtraBold.woff2
  src/fonts/woff2/Pretendard-ExtraLight.woff2
  src/fonts/woff2/Pretendard-Light.woff2
  src/fonts/woff2/Pretendard-Medium.woff2
  src/fonts/woff2/Pretendard-Regular.woff2
  src/fonts/woff2/Pretendard-SemiBold.woff2
  src/fonts/woff2/Pretendard-Thin.woff2
  src/pages/Home.tsx
  src/pages/users/SignupId.tsx
  src/pages/users/SignupPs.tsx
  src/theme/theme.ts
Labels: ✨ Feature, 🎨 Html&css

#7 Feature: social login
  src/App.tsx
  src/assets/icons/AlarmIcon.png
  src/assets/icons/MenuIcon.png
  src/assets/icons/Naver_Button.png
  src/assets/icons/kakao_Button.png
  src/components/SignInForm.tsx
  src/components/SignUpForm.tsx
  src/components/shared/DefaultIcon.tsx
  src/components/shared/HomeAppBar.tsx
  src/components/shared/MainDrawer.tsx
  src/components/user/SignupIdForm.tsx
  src/components/user/SignupPsForm.tsx
  src/pages/Home.tsx
  src/pages/KakaoLogin.tsx
  src/pages/NaverLogin.tsx
  src/pages/users/SignIn.tsx
  src/pages/users/SignupId.tsx
Labels: 📬 API, ✨ Feature, 🎨 Html&css

#10 Feature: home maincard
  package-lock.json
  package.json
  src/components/main/MainCarousel.tsx
  src/pages/Home.tsx
Labels: ✨ Feature, 🎨 Html&css

#12 Feature sales detail layout
  src/App.css
  src/App.tsx
  src/assets/icons/CloseIcon.png
  src/assets/icons/RightArrowGrey.png
  src/assets/icons/RightArrowPurple.png
  src/components/detail/SellerDrawer.tsx
  src/components/detail/SellerInfoButton.tsx
  src/components/detail/VideoCard.tsx
  src/components/drawer/CategoryCard.tsx
  src/components/shared/AppBarWithDrawer.tsx
  src/components/shared/CustomDivider.tsx
  src/components/shared/HorizontalContainer.tsx
  src/components/shared/SimpleAppBar.tsx
  src/components/user/SignupIdForm.tsx
  src/components/user/SignupPsForm.tsx
  src/pages/Home.tsx
  src/pages/detail/ProductDetail.tsx
  src/pages/users/SignupId.tsx
  src/pages/users/SignupPs.tsx
Labels: ✨ Feature, 🎨 Html&css

#13 feature: video player for product
  package-lock.json
  package.json
  src/components/detail/VideoCard.tsx
  src/components/detail/VideoPlayer.tsx
  src/components/drawer/CategoryCard.tsx
  src/pages/detail/ProductDetail.tsx
Labels: ✨ Feature, 🎨 Html&css

#14 Feature make gather
  package.json
  src/App.tsx
  src/assets/icons/Copyicon.png
  src/assets/icons/Plus.png
  src/assets/icons/QuestionMark.png
  src/components/club/ClubStartBase.tsx
  src/components/club/KeywordComponet.module.css
  src/components/club/KeywordComponet.tsx
  src/components/club/ParticipateCodeInput.module.css
  src/components/club/ParticipateCodeInput.tsx
  src/components/club/PopupBubble.tsx
  src/components/club/RegisterClubPurpose.module.css
  src/components/club/RegisterClubPurpose.tsx
  src/components/shared/FormButton.tsx
  src/pages/club/ClubFirstStep.tsx
  src/pages/club/MakeClubDes.module.css
  src/pages/club/MakeClubDes.tsx
  src/pages/club/MakeClubKeywords.tsx
  src/pages/club/MakeClubNaming.module.css
  src/pages/club/MakeClubNaming.tsx
  src/pages/club/MakeClubProfile.module.css
  src/pages/club/MakeClubProfile.tsx
  src/pages/club/MakeClubRegister.module.css
  src/pages/club/MakeClubRegister.tsx
Labels: ✨ Feature, 🎨 Html&css

#15 Feature/main my buying cards
  src/App.tsx
  src/components/SignInForm.tsx
  src/components/main/MainCarousel.tsx
  src/components/main/MyBuyingCard.tsx
  src/index.tsx
  src/pages/Home.tsx
  src/pages/detail/ProductDetail.tsx
  src/utils/axiosInterceptor.tsx
Labels: 🐞 BugFix, 📬 API, ✨ Feature, 🎨 Html&css

#17 fix: errors occured in merge
  src/App.tsx
  src/components/club/ClubStartBase.tsx
Labels: 🐞 BugFix

#18 Feature/club axios local
  src/components/SignInForm.tsx
  src/pages/club/MakeClubProfile.tsx
  src/states/userInfo.ts
  src/utils/axiosInterceptor.tsx
Labels: ✨ Feature, 🔨 Refactor

#21 add: docker file 및 nginx.conf 파일 생성
  Dockerfile
  nginx.conf
Labels: 🌎 Deploy

#22 Feature/tabbar
  package-lock.json
  package.json
  src/App.tsx
  src/assets/categoryImages/aniplant.png
  src/assets/categoryImages/coupon.png
  src/assets/categoryImages/digital.png
  src/assets/categoryImages/fashion.png
  src/assets/categoryImages/food.png
  src/assets/categoryImages/funiture.png
  src/assets/categoryImages/hobby.png
  src/assets/categoryImages/life.png
  src/assets/categoryImages/overseas.png
  src/assets/categoryImages/sports.png
  src/assets/categoryImages/travel.png
  src/assets/icons/ClubIcon.png
  src/assets/icons/HomeIcon.png
  src/assets/icons/MyIcon.png
  src/assets/icons/flaming.gif
  src/components/drawer/CategoryCard.tsx
  src/components/drawer/MainDrawer.tsx
  src/components/drawer/SearchBar.tsx
  src/components/main/MyBuyingCard.tsx
  src/components/main/MyBuyingCardComponents.tsx
  src/components/shared/BottomTabBar.tsx
  src/components/shared/DefaultContainer.tsx
  src/components/shared/HomeAppBar.tsx
  src/pages/AutoComplete.tsx
  src/pages/ChargeCash.tsx
  src/pages/club/Club.tsx
  src/pages/club/JoinClubProfile.tsx
  src/pages/club/JoinClubRegister.tsx
  src/pages/club/MakeClubDes.tsx
  src/pages/club/MakeClubNaming.tsx
  src/pages/club/MakeClubProfile.tsx
  src/pages/club/MakeClubRegister.tsx
  src/pages/club/style/MakeClubDes.module.css
  src/pages/club/style/MakeClubNaming.module.css
  src/pages/club/style/MakeClubProfile.module.css
  src/pages/club/style/MakeClubRegister.module.css
  src/pages/home/Home.tsx
  src/pages/myinfo/MyInfo.tsx
  tsconfig.json
Labels: ✨ Feature, 🎨 Html&css, ✅ Test

#25 feature: auto complete in SearchBar
  src/components/drawer/SearchBar.tsx
  src/pages/AutoComplete.tsx
Labels: ✨ Feature

#27 feature/kakao-share
  .env
  .gitignore
  global.d.ts
  package.json
  public/index.html
  src/assets/temperImages/Group 436.png
  src/index.tsx
  src/pages/club/MakeClubRegister.tsx
Labels: ✨ Feature, 🎨 Html&css

#28 Feature/home clubbuyingcards
  package.json
  src/App.tsx
  src/assets/icons/FullScreen.png
  src/assets/icons/StarIconEmpty.svg
  src/assets/icons/StarIconFilled.svg
  src/assets/logo/MoyeoLogo.png
  src/components/detail/VideoPlayer.tsx
  src/components/drawer/CategoryCard.tsx
  src/components/main/ClubBuyingCard.tsx
  src/components/main/MyBuyingCard.tsx
  src/components/main/MyBuyingCardComponents.tsx
  src/components/shared/AppBarWithDrawer.tsx
  src/components/shared/BottomTabBar.tsx
  src/components/shared/SimpleAppBar.tsx
  src/pages/club/Club.tsx
  src/pages/home/Home.tsx
  src/pages/myinfo/FontSetting.tsx
  src/pages/myinfo/MyInfo.tsx
Labels: ✨ Feature, 🎨 Html&css

#29 feature/Kakao-share
  src/App.tsx
  src/assets/clubRankImage/1_dong_mountain.png
  src/assets/clubRankImage/2_cheonggye_mountain.png
  src/assets/clubRankImage/3_seolak_mountain.png
  src/assets/clubRankImage/4_jiri_mountain.png
  src/assets/clubRankImage/5_halla_mountain.png
  src/components/SignInForm.tsx
  src/components/club/ClubRankInfoBox.module.css
  src/components/club/ClubRankInfoBox.tsx
  src/pages/club/ClubDetail.tsx
  src/pages/club/MyClubs.tsx
  src/utils/newAxiosInterceptor.tsx
Labels: ✨ Feature, 🎨 Html&css

#30 feature: recommend card styling
  src/assets/Images/Empty_Data.png
  src/components/main/ClubBuyingCard.tsx
  src/components/main/MainCarousel.tsx
  src/components/main/RecommendBox.tsx
  src/components/myinfo/MyInfoCard.tsx
  src/components/shared/AppBarWithDrawer.tsx
  src/pages/home/Home.tsx
  src/pages/myinfo/MyInfo.tsx
Labels: ✨ Feature, 🎨 Html&css

#31 feature/ClubList
  src/App.tsx
  src/assets/faceImage/SadFaceImage.png
  src/assets/icons/DownArrowGrey.png
  src/components/club/ClubProductNo.module.css
  src/components/club/ClubProductNo.tsx
  src/components/club/ClubRankInfoBox.module.css
  src/components/club/ClubRankInfoBox.tsx
  src/components/main/ClubBuyingCard.tsx
  src/pages/club/MakeClubRegister.tsx
  src/pages/club/MyClubs.tsx
  src/pages/club/MyClubsAll.tsx
  src/pages/club/style/MyClubs.module.css
Labels: ✨ Feature, 🎨 Html&css

#32 feature/ClubDetail
  src/App.tsx
  src/assets/icons/PulsNoBackground.png
  src/components/club/ClubIsJoinedPopup.module.css
  src/components/club/ClubIsJoinedPopup.tsx
  src/components/club/ClubRankInfoBox.module.css
  src/components/club/ClubRankInfoBox.tsx
  src/components/main/MyBuyingCardComponents.tsx
  src/pages/club/ClubDetail.tsx
  src/pages/club/MyClubDetail.tsx
  src/pages/club/MyClubs.tsx
  src/pages/club/MyClubsAll.tsx
  src/pages/club/style/ClubDetail.module.css
Labels: ✨ Feature, 🎨 Html&css

#33 Feature/product detail
  src/App.tsx
  src/components/SignInForm.tsx
  src/components/detail/AchievementGraph.tsx
  src/components/detail/ProductInfoSection.tsx
  src/components/detail/SellerDrawer.tsx
  src/components/detail/TabPanel.tsx
  src/components/main/ClubBuyingCard.tsx
  src/components/main/MainCarousel.tsx
  src/components/main/MyBuyingCard.tsx
  src/components/main/RecommendBox.tsx
  src/pages/detail/ProductDetail.tsx
Labels: ✨ Feature, 🎨 Html&css

#35 feature: home api connect
  package.json
  src/App.tsx
  src/components/SignInForm.tsx
  src/components/detail/AchievementGraph.tsx
  src/components/detail/ProductInfoSection.tsx
  src/components/main/ClubBuyingCard.tsx
  src/components/main/MyBuyingCard.tsx
  src/components/main/RecommendBox.tsx
  src/pages/detail/ProductDetail.tsx
  src/pages/home/Home.tsx
Labels: 📬 API, ✨ Feature, 🎨 Html&css

#34 Feature/my club detail
  src/App.tsx
  src/assets/clubMap/MapPage.png
  src/assets/clubMap/RedFlag.png
  src/components/club/ClubJoinMemberPopup.module.css
  src/components/club/ClubJoinMemberPopup.tsx
  src/components/main/MyBuyingCardComponents.tsx
  src/pages/club/ClubMountainMap.tsx
  src/pages/club/MyClubDetail.tsx
  src/pages/club/style/ClubDetail.module.css
  src/pages/club/style/ClubMountainMap.module.css
Labels: ✨ Feature, 🎨 Html&css

#38 feature/connect
  package.json
  src/components/club/ClubIsJoinedPopup.module.css
  src/components/club/ClubIsJoinedPopup.tsx
  src/components/club/ClubRankInfoBox.module.css
  src/components/club/ClubRankInfoBox.tsx
  src/pages/club/MyClubDetail.tsx
  src/pages/club/MyClubs.tsx
  src/pages/club/MyClubsAll.tsx
  src/pages/club/style/ClubDetail.module.css
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css

#39 fix/link-connect
  src/components/club/KeywordComponet.module.css
  src/components/club/KeywordComponet.tsx
  src/pages/club/JoinClubRegister.tsx
  src/pages/club/MakeClubKeywords.tsx
  src/pages/club/MakeClubRegister.tsx
  src/pages/club/MyClubs.tsx
  src/pages/club/style/MakeClubRegister.module.css
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css, 🔨 Refactor

#40 feat: 잔액 충전 연결
  src/App.tsx
  src/pages/ChargeCash.tsx
Labels: 📬 API

#41 feature: etc-styling
  src/assets/logo/Login_logo.png
  src/components/detail/ProductInfoSection.tsx
  src/components/detail/SellerDrawer.tsx
  src/components/detail/SellerInfoButton.tsx
  src/components/drawer/CategoryCard.tsx
  src/components/main/ClubBuyingCard.tsx
  src/components/main/MainCarousel.tsx
  src/components/main/MyBuyingCard.tsx
  src/components/main/MyBuyingCardComponents.tsx
  src/components/main/RecommendBox.tsx
  src/components/shared/AppBarWithDrawer.tsx
  src/components/shared/BottomTabBar.tsx
  src/pages/detail/ProductDetail.tsx
  src/pages/home/Home.tsx
  src/pages/search/Search.tsx
  src/pages/users/SignIn.tsx
  src/utils/axiosInterceptor.tsx
Labels: 🐞 BugFix, 🎨 Html&css

#42 feature/splash
  src/App.tsx
  src/assets/logo/MainLogo.png
  src/assets/splash/FirstImage.png
  src/assets/splash/SecondImage.png
  src/assets/splash/ThirdImage.png
  src/pages/club/MyClubsAll.tsx
  src/pages/splash/Splash.module.css
  src/pages/splash/Splash.tsx
  src/pages/splash/SplashAdvertisement.module.css
  src/pages/splash/SplashAdvertisement.tsx
Labels: ✨ Feature, 🎨 Html&css

#43 featue/noClub
  src/pages/club/MyClubs.tsx
  src/pages/club/style/MyClubs.module.css
Labels: 🐞 BugFix, 🎨 Html&css

#44 Fix/thumbnail img
  src/components/detail/SellerDrawer.tsx
  src/components/detail/SellerInfoButton.tsx
  src/components/main/RecommendBox.tsx
  src/pages/home/Home.tsx
Labels: 🐞 BugFix

#45 feature: notification, add main carousl images
  package.json
  src/assets/advertise/Sale_Dish.png
  src/assets/advertise/Sale_Mask.png
  src/assets/advertise/Sale_Trip.png
  src/components/main/MainCarousel.tsx
  src/components/shared/AppBarWithDrawer.tsx
  src/pages/detail/ProductDetail.tsx
Labels: ✨ Feature, 🎨 Html&css

#46 fix/pageinfolack? block
  src/pages/club/JoinClubProfile.tsx
  src/pages/club/JoinClubRegister.tsx
  src/pages/club/MakeClubKeywords.tsx
  src/pages/club/MakeClubProfile.tsx
  src/pages/club/MakeClubRegister.tsx
  src/pages/club/style/MakeClubProfile.module.css
  src/pages/home/Home.tsx
Labels: 🐞 BugFix, 📬 API

#47 feature/charge
  src/App.tsx
  src/assets/icons/NotCheckedIcon.png
  src/components/shared/DefaultContainer.tsx
  src/pages/ChargeCash.tsx
  src/pages/charge/ChargeCash.module.css
  src/pages/charge/ChargeCash.tsx
Labels: ✨ Feature, 🎨 Html&css

#48 Feature/my fix
  package.json
  src/pages/club/MakeClubProfile.tsx
  src/pages/club/MyClubDetail.tsx
  src/pages/club/MyClubs.tsx
  src/pages/club/style/ClubDetail.module.css
Labels: 🐞 BugFix, 🎨 Html&css

#50 fix/myPage
  src/pages/myinfo/MyInfo.module.css
  src/pages/myinfo/MyInfo.tsx
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css

#52 finally fix
  package.json
  src/pages/myinfo/MyInfo.tsx
Labels: 🐞 BugFix

#57 Feature/flow fix
  src/App.tsx
  src/components/user/SignupPsForm.tsx
  src/pages/KakaoLogin.tsx
  src/pages/NaverLogin.tsx
  src/pages/club/ClubMountainMap.tsx
  src/pages/club/JoinClubRegister.tsx
  src/pages/club/MakeClubProfile.tsx
  src/pages/club/MakeClubRegister.tsx
  src/pages/club/MyClubDetail.tsx
  src/pages/club/style/ClubDetail.module.css
  src/pages/club/style/ClubMountainMap.module.css
  src/pages/myinfo/FontSetting.tsx
  src/pages/myinfo/MyInfo.tsx
  src/pages/splash/Splash.tsx
  src/pages/splash/SplashAdvertisement.tsx
Labels: 🐞 BugFix

#60 fix/club
  src/pages/club/JoinClubProfile.tsx
  src/pages/club/MyClubDetail.tsx
Labels: 🐞 BugFix

#62 fix
  src/pages/club/MakeClubRegister.tsx
Labels: 🐞 BugFix
